### PR TITLE
fix issue #8

### PR DESCRIPTION
**Pull request by ezhasyafaat**
## Description

Generate command not automatically registered in leaf

### CODE REVIEW

**Comment by Kristories** [comment]
Yes I confirm the bug exists. Commands are not automatically registered, but this issue will be fixed by simply double-quoting the first parameter.
Can you check @mychidarko

**Comment by mychidarko** [comment]
Hey guys, thanks for the pull and the comment. I'll check this out 🙏🏽

**Comment by Kristories** [comment]
IMO, it's better to use `preg_replace` instead of `str_replace`, as it can create duplication.

```
aloeContents = file_get_contents($aloe);
$replace = "\$console->register(\App\Console\\$className::class);\n\$console->register(";
$aloeContents = preg_replace('/\$console->register\(/', $replace, $aloeContents, 1);
```

We can use the optional parameter `offset`.

**Comment by ezhasyafaat** [comment]
I confirm it's another bug, but I can do it in this PR. What do you think @mychidarko ?

**Comment by mychidarko** [comment]
Yeah sure

**Review by Kristories — APPROVED** [review]
LGTM

**Review by mychidarko — APPROVED** [review]
This looks great, thanks guys.

**Pull request merged**
